# define the network
networks:
    web-network:
services:
    web:
        container_name: web
        domainname: "mqtt.local"
        environment:
            NGINX_HOST: "mqtt.local"
            NGINX_PORT: "80"
            NGINX_ROOT: "/app/public"
            PHP_HANDLER_NAME: 'php'
            PHP_HANDLER_PORT: '9000'
        command: >
            /bin/bash -c
            "echo "" > /var/log/nginx/app_access.log
            && echo "" > /var/log/nginx/app_error.log
            && envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT $$PHP_HANDLER_NAME $$PHP_HANDLER_PORT' < /etc/nginx/conf.d/default.conf.tpl > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile-Nginx
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./docker/nginx/conf:/etc/nginx/conf.d:rw
            - ./docker/data/log/nginx/:/var/log/nginx/
        depends_on:
            - php
        links:
            - php
        tty: true
        networks:
            - web-network
    php:
        container_name: php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - PHP_VERSION=8.1
        ports:
            - "9000:9000"
        working_dir: /app
        volumes:
            - .:/app:rw
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mariadb
        links:
            - mariadb
        restart: always
        tty: true
        networks:
            - web-network
        command: '/bin/bash -c "cd /app && composer install && php-fpm"'
#    node:
#        container_name: node
#        build:
#            context: ./ # use root folder to allow mount from docker-compose
#            dockerfile: docker/node/Dockerfile-Node
#            args:
#                - NODE_VERSION=18.9-alpine
#        ports:
#            - "8080:8080"
#        volumes:
#            - .:/app:rw
#        command: '/bin/sh -c "cd /app && npm install && npm run dev-server"'
#        links:
#            - web
#        networks:
#            - web-network
    mariadb:
        container_name: mariadb
        image: mariadb:10.5.17
        volumes:
            - ./docker/data/db:/var/lib/mysql:rw
            - ./docker/mariadb:/etc/mysql/conf.d
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mqtt
            MYSQL_USER: mqtt
            MYSQL_PASSWORD: mqtt
        networks:
            - web-network
    maildev:
        container_name: maildev
        image: maildev/maildev:latest
        command: maildev --hide-extensions STARTTLS
        ports:
            - "1025:1025"
            - "1080:1080"
        links:
            - php
            - web
        networks:
            - web-network
    rabbitmq:
        container_name: rabittmq
        image: rabbitmq:3.11-management
        hostname: rabbit
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
        ports:
            - "5672:5672"
            - "15672:15672"
            - "1883:1883"
        networks:
            - web-network